"""Generate PyInstaller Windows version resources from validated source metadata."""

from __future__ import annotations

import argparse
from pathlib import Path

from release_metadata import load_release_metadata


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--expected-tag")
    args = parser.parse_args()
    metadata = load_release_metadata(expected_tag=args.expected_tag)
    version_tuple = tuple(int(part) for part in metadata["version"].split(".")) + (0,)
    dotted_version = f"{metadata['version']}.0"
    content = f"""# Generated by scripts/generate_version_info.py; do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={version_tuple!r},
    prodvers={version_tuple!r},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
          StringStruct('CompanyName', 'AegisVault contributors'),
          StringStruct('FileDescription', 'AegisVault local encryption utility'),
          StringStruct('FileVersion', '{dotted_version}'),
          StringStruct('InternalName', '{metadata["app_name"]}'),
          StringStruct('LegalCopyright', 'Copyright (c) AegisVault contributors'),
          StringStruct('OriginalFilename', '{metadata["exe_name"]}'),
          StringStruct('ProductName', '{metadata["app_name"]}'),
          StringStruct('ProductVersion', '{dotted_version}'),
        ],
      )
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ],
)
"""
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8", newline="\n")
    print(args.output.resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
